name: Publish package to the Maven Central Repository
on:
  push: 
    branches: [ "main" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
#           server-username: ashrithgowda
#           server-password: Viratbats@03
      - name: Publish package
        run: |
          mvn verify -Dgpg.passphrase=admin
          mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ashrithgowda
          MAVEN_PASSWORD: Viratbats@03
