name: Deploy to central repositories

on:
  push:
    tags:
    - '*'
    branches: [ "main" ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
          allowUpdates: true
          artifacts: "${{ github.workspace }}/target/*.jar"
    - name: Publish to the Maven Central Repository
      run: mvn deploy
      env:
          MAVEN_USERNAME: ashrithgowda
          MAVEN_PASSWORD: Viratbats@03
